import { Outfit } from "next/font/google";
import "./globals.css";
import "remixicon/fonts/remixicon.css";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Add or adjust weights
  variable: "--font-outfit", // Optional if you want to use CSS var
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.className}> antialiased px-8 `}>
        {children}
      </body>
    </html>
  );
}
