import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/ui/Footer/Footer";
import FooterHero from "@/ui/Footer/FooterHero";
import Header from "@/ui/Header/Header";
import BottomNav from "@/ui/BottomNav/BottomNav";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  `}
      >
        <Header />
        <main className="px-4 md:px-16"> {children}</main>
        <FooterHero />
        <BottomNav />
        <Footer />
      </body>
    </html>
  );
}
